# CC=gcc or clang or gcc-13 (on OSX)
CC=gcc

# Math, big numbers and SDL2 fonts
LDLIBS=-lm

ifeq ($(shell uname -s), Darwin)
   LDLIBS += -framework OpenGL -framework GLUT
else
   LDLIBS += -lglut -lGLU -lGL
endif

# The DEBUG_LEVEL (OFF, CRITICAL, ERROR, WARNING, INFO, TRACE)
# is set by default to WARNING in error.h.
# To set it on the command line, force compilation and set it.
# Example: make -B CFLAGS="-DDEBUG_LEVEL=INFO" to see all debug messages
# above the 'INFO' level.

# clang 14.0.3 does implement the C23 feature __VA_OPTS__ but issues a spurious
# warning. The -Wno-gnu-zero-variadic-macro-arguments disables this warning.
# This flag is ignored by gcc (which implements __VA_OPTS__ without any warning).
override CFLAGS += -std=gnu2x -MMD -Wall -pedantic -Wextra -Wshadow -Wpointer-arith	\
-Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wno-unused-parameter

SOURCES := $(wildcard *.c)
OBJECTS := $(SOURCES:%.c=%.o)
DEPS := $(SOURCES:%.c=%.d)

# Compilation in debug mode by default, to use gdb and valgrind. Warnings produce an error.
LDLIBS += $(shell sdl2-config --libs)

all: CFLAGS += -g -O0 -Werror $(shell sdl2-config --cflags)
all: tp

# Once the program works, optimized mode (and no error in case of warning).
nowerror: CFLAGS += -O3 -Wunused-parameter
nowerror: tp

# Add parser.o scan.o if bison/flex interface.
tp: $(OBJECTS)
	$(CC) -o $@ $(LDFLAGS) $(CFLAGS) $^ $(LDLIBS)

# Include dependancies generated by gcc -MMD.
-include $(DEPS)

# Clean all.
.PHONY: clean
clean:
	rm -rf tp *.o *.d TAGS core
